export interface Business {
  id: string;
  name: string;
  slug: string;
  category: string;
  subcategory?: string;
  description: string;
  phone: string;
  email: string;
  website?: string;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  hours: {
    monday?: string;
    tuesday?: string;
    wednesday?: string;
    thursday?: string;
    friday?: string;
    saturday?: string;
    sunday?: string;
  };
  services: string[];
  rating: number;
  reviewCount: number;
  established?: number;
  logo?: string;
  images?: string[];
  socialMedia?: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
    linkedin?: string;
  };
  featured: boolean;
  verified: boolean;
}

export const businesses: Business[] = [
  {
    id: "1",
    slug: "sunrise-plumbing-services",
    name: "Sunrise Plumbing Services",
    category: "Home Services",
    subcategory: "Plumbing",
    description:
      "Professional plumbing services for residential and commercial properties. We offer 24/7 emergency services, pipe repair, drain cleaning, water heater installation, and complete bathroom renovations. With over 15 years of experience, our licensed plumbers deliver quality workmanship at competitive prices.",
    phone: "+1 (555) 123-4567",
    email: "info@sunriseplumbing.com",
    website: "https://sunriseplumbing.com",
    address: "123 Main Street",
    city: "Springfield",
    state: "IL",
    zipCode: "62701",
    hours: {
      monday: "7:00 AM - 6:00 PM",
      tuesday: "7:00 AM - 6:00 PM",
      wednesday: "7:00 AM - 6:00 PM",
      thursday: "7:00 AM - 6:00 PM",
      friday: "7:00 AM - 6:00 PM",
      saturday: "8:00 AM - 4:00 PM",
      sunday: "Emergency Only",
    },
    services: [
      "Pipe Repair & Replacement",
      "Drain Cleaning",
      "Water Heater Installation",
      "Bathroom Renovation",
      "Leak Detection",
      "Sewer Line Services",
      "24/7 Emergency Service",
    ],
    rating: 4.8,
    reviewCount: 342,
    established: 2008,
    featured: true,
    verified: true,
    socialMedia: {
      facebook: "https://facebook.com/sunriseplumbing",
      instagram: "https://instagram.com/sunriseplumbing",
    },
  },
  {
    id: "2",
    slug: "green-leaf-restaurant",
    name: "Green Leaf Restaurant",
    category: "Food & Dining",
    subcategory: "Restaurants",
    description:
      "A farm-to-table dining experience featuring seasonal menus crafted from locally sourced ingredients. Our chef creates innovative dishes inspired by Mediterranean and Asian cuisines. Private dining room available for events up to 40 guests.",
    phone: "+1 (555) 234-5678",
    email: "reservations@greenleafrestaurant.com",
    website: "https://greenleafrestaurant.com",
    address: "456 Oak Avenue",
    city: "Springfield",
    state: "IL",
    zipCode: "62702",
    hours: {
      monday: "Closed",
      tuesday: "11:00 AM - 10:00 PM",
      wednesday: "11:00 AM - 10:00 PM",
      thursday: "11:00 AM - 10:00 PM",
      friday: "11:00 AM - 11:00 PM",
      saturday: "10:00 AM - 11:00 PM",
      sunday: "10:00 AM - 9:00 PM",
    },
    services: [
      "Dine-In",
      "Takeout",
      "Catering",
      "Private Dining",
      "Wine Pairing",
      "Vegetarian & Vegan Options",
    ],
    rating: 4.6,
    reviewCount: 218,
    established: 2015,
    featured: true,
    verified: true,
    socialMedia: {
      facebook: "https://facebook.com/greenleafrestaurant",
      instagram: "https://instagram.com/greenleafrestaurant",
    },
  },
  {
    id: "3",
    slug: "tech-solutions-pro",
    name: "Tech Solutions Pro",
    category: "Technology",
    subcategory: "IT Services",
    description:
      "Comprehensive IT support and technology solutions for small and medium businesses. We provide managed IT services, cybersecurity, cloud migration, network setup, and 24/7 helpdesk support. Our certified technicians ensure your business runs smoothly.",
    phone: "+1 (555) 345-6789",
    email: "support@techsolutionspro.com",
    website: "https://techsolutionspro.com",
    address: "789 Tech Park Drive",
    city: "Springfield",
    state: "IL",
    zipCode: "62703",
    hours: {
      monday: "8:00 AM - 8:00 PM",
      tuesday: "8:00 AM - 8:00 PM",
      wednesday: "8:00 AM - 8:00 PM",
      thursday: "8:00 AM - 8:00 PM",
      friday: "8:00 AM - 6:00 PM",
      saturday: "9:00 AM - 5:00 PM",
      sunday: "Closed",
    },
    services: [
      "Managed IT Services",
      "Cybersecurity",
      "Cloud Migration",
      "Network Setup",
      "Data Backup & Recovery",
      "Software Development",
      "24/7 Helpdesk",
    ],
    rating: 4.9,
    reviewCount: 156,
    established: 2012,
    featured: false,
    verified: true,
    socialMedia: {
      linkedin: "https://linkedin.com/company/techsolutionspro",
      twitter: "https://twitter.com/techsolutionspro",
    },
  },
  {
    id: "4",
    slug: "bright-smile-dental",
    name: "Bright Smile Dental",
    category: "Healthcare",
    subcategory: "Dentistry",
    description:
      "Family dental practice offering comprehensive dental care in a comfortable and welcoming environment. From routine cleanings to cosmetic dentistry, implants, and orthodontics — we have your complete dental health covered. We accept most insurance plans.",
    phone: "+1 (555) 456-7890",
    email: "appointments@brightsmileddental.com",
    address: "321 Health Boulevard",
    city: "Springfield",
    state: "IL",
    zipCode: "62704",
    hours: {
      monday: "8:00 AM - 5:00 PM",
      tuesday: "8:00 AM - 5:00 PM",
      wednesday: "8:00 AM - 7:00 PM",
      thursday: "8:00 AM - 5:00 PM",
      friday: "8:00 AM - 3:00 PM",
      saturday: "9:00 AM - 2:00 PM",
      sunday: "Closed",
    },
    services: [
      "General Dentistry",
      "Teeth Whitening",
      "Dental Implants",
      "Orthodontics",
      "Emergency Dental Care",
      "Pediatric Dentistry",
      "Cosmetic Dentistry",
    ],
    rating: 4.7,
    reviewCount: 289,
    established: 2005,
    featured: true,
    verified: true,
  },
  {
    id: "5",
    slug: "elite-fitness-gym",
    name: "Elite Fitness Gym",
    category: "Health & Fitness",
    subcategory: "Gyms",
    description:
      "State-of-the-art fitness facility with over 10,000 sq ft of equipment, group fitness classes, personal training, and nutrition counseling. We offer flexible membership plans to fit every budget and fitness goal. Free childcare available during gym hours.",
    phone: "+1 (555) 567-8901",
    email: "membership@elitefitnessgym.com",
    website: "https://elitefitnessgym.com",
    address: "654 Fitness Way",
    city: "Springfield",
    state: "IL",
    zipCode: "62705",
    hours: {
      monday: "5:00 AM - 11:00 PM",
      tuesday: "5:00 AM - 11:00 PM",
      wednesday: "5:00 AM - 11:00 PM",
      thursday: "5:00 AM - 11:00 PM",
      friday: "5:00 AM - 10:00 PM",
      saturday: "6:00 AM - 9:00 PM",
      sunday: "7:00 AM - 8:00 PM",
    },
    services: [
      "Weight Training",
      "Cardio Equipment",
      "Group Fitness Classes",
      "Personal Training",
      "Nutrition Counseling",
      "Swimming Pool",
      "Sauna & Steam Room",
    ],
    rating: 4.5,
    reviewCount: 412,
    established: 2018,
    featured: false,
    verified: true,
    socialMedia: {
      instagram: "https://instagram.com/elitefitnessgym",
      facebook: "https://facebook.com/elitefitnessgym",
    },
  },
  {
    id: "6",
    slug: "golden-paws-pet-salon",
    name: "Golden Paws Pet Salon",
    category: "Pet Services",
    subcategory: "Pet Grooming",
    description:
      "Professional pet grooming services for dogs and cats of all breeds and sizes. Our experienced groomers provide bathing, haircuts, nail trimming, teeth brushing, and full spa treatments. We use only natural, pet-safe products.",
    phone: "+1 (555) 678-9012",
    email: "book@goldenpawssalon.com",
    address: "987 Pet Lane",
    city: "Springfield",
    state: "IL",
    zipCode: "62706",
    hours: {
      monday: "9:00 AM - 6:00 PM",
      tuesday: "9:00 AM - 6:00 PM",
      wednesday: "9:00 AM - 6:00 PM",
      thursday: "9:00 AM - 6:00 PM",
      friday: "9:00 AM - 6:00 PM",
      saturday: "8:00 AM - 5:00 PM",
      sunday: "10:00 AM - 3:00 PM",
    },
    services: [
      "Dog Grooming",
      "Cat Grooming",
      "Bath & Brush",
      "Haircuts & Styling",
      "Nail Trimming",
      "Teeth Brushing",
      "Flea Treatment",
    ],
    rating: 4.8,
    reviewCount: 187,
    established: 2019,
    featured: false,
    verified: true,
    socialMedia: {
      instagram: "https://instagram.com/goldenpawssalon",
      facebook: "https://facebook.com/goldenpawssalon",
    },
  },

  // ── Texas, USA Businesses ──────────────────────────────────────────────────

  {
    id: "7",
    slug: "franklins-barbecue-austin",
    name: "Franklin Barbecue",
    category: "Food & Dining",
    subcategory: "BBQ Restaurant",
    description:
      "Widely regarded as the best BBQ in the United States, Franklin Barbecue in Austin, TX has been serving legendary Central Texas-style smoked brisket, ribs, and pulled pork since 2009. Pitmasters Aaron and Stacy Franklin have won multiple James Beard Awards. Lines form before sunrise — and every bite is worth the wait.",
    phone: "+1 (512) 653-1187",
    email: "info@franklinbbq.com",
    website: "https://franklinbbq.com",
    address: "900 E 11th St",
    city: "Austin",
    state: "TX",
    zipCode: "78702",
    hours: {
      monday: "Closed",
      tuesday: "11:00 AM - Sold Out",
      wednesday: "11:00 AM - Sold Out",
      thursday: "11:00 AM - Sold Out",
      friday: "11:00 AM - Sold Out",
      saturday: "11:00 AM - Sold Out",
      sunday: "11:00 AM - Sold Out",
    },
    services: [
      "Dine-In",
      "Takeout",
      "Smoked Brisket",
      "Pork Ribs",
      "Pulled Pork",
      "House-Made Sides",
      "Catering (Limited)",
    ],
    rating: 4.9,
    reviewCount: 8742,
    established: 2009,
    featured: true,
    verified: true,
    socialMedia: {
      twitter: "https://twitter.com/franklinbbq",
      instagram: "https://instagram.com/franklinbbq",
      facebook: "https://facebook.com/franklinbbq",
    },
  },
  {
    id: "8",
    slug: "whataburger-san-antonio",
    name: "Whataburger",
    category: "Food & Dining",
    subcategory: "Fast Food",
    description:
      "A Texas institution since 1950, Whataburger was founded in Corpus Christi and has grown to over 900 locations. Known for made-to-order burgers on five-inch buns, fresh-never-frozen beef, and 24/7 service. The San Antonio flagship near the original Corpus Christi location is a must-visit for Texas food heritage.",
    phone: "+1 (210) 476-7300",
    email: "customersupport@whataburger.com",
    website: "https://whataburger.com",
    address: "3833 N St Mary's St",
    city: "San Antonio",
    state: "TX",
    zipCode: "78212",
    hours: {
      monday: "Open 24 Hours",
      tuesday: "Open 24 Hours",
      wednesday: "Open 24 Hours",
      thursday: "Open 24 Hours",
      friday: "Open 24 Hours",
      saturday: "Open 24 Hours",
      sunday: "Open 24 Hours",
    },
    services: [
      "Dine-In",
      "Drive-Thru",
      "Takeout",
      "Delivery",
      "Breakfast All Day",
      "Mobile App Ordering",
      "Catering",
    ],
    rating: 4.5,
    reviewCount: 5120,
    established: 1950,
    featured: false,
    verified: true,
    socialMedia: {
      twitter: "https://twitter.com/whataburger",
      instagram: "https://instagram.com/whataburger",
      facebook: "https://facebook.com/whataburger",
    },
  },
  {
    id: "9",
    slug: "methodist-hospital-houston",
    name: "Houston Methodist Hospital",
    category: "Healthcare",
    subcategory: "Hospital",
    description:
      "Houston Methodist Hospital is consistently ranked as one of the top hospitals in the United States by U.S. News & World Report. Located in the Texas Medical Center — the world's largest medical complex — it offers nationally recognized care in cardiology, oncology, neurology, orthopedics, and organ transplantation.",
    phone: "+1 (713) 790-3311",
    email: "patientexperience@houstonmethodist.org",
    website: "https://houstonmethodist.org",
    address: "6565 Fannin St",
    city: "Houston",
    state: "TX",
    zipCode: "77030",
    hours: {
      monday: "Open 24 Hours",
      tuesday: "Open 24 Hours",
      wednesday: "Open 24 Hours",
      thursday: "Open 24 Hours",
      friday: "Open 24 Hours",
      saturday: "Open 24 Hours",
      sunday: "Open 24 Hours",
    },
    services: [
      "Emergency Care",
      "Cardiology",
      "Oncology",
      "Neurology",
      "Orthopedics",
      "Organ Transplantation",
      "Robotic Surgery",
      "Primary Care",
    ],
    rating: 4.7,
    reviewCount: 3891,
    established: 1919,
    featured: true,
    verified: true,
    socialMedia: {
      twitter: "https://twitter.com/methodisthosp",
      facebook: "https://facebook.com/houstonmethodist",
      instagram: "https://instagram.com/houstonmethodist",
    },
  },
  {
    id: "10",
    slug: "jw-marriott-dallas",
    name: "JW Marriott Dallas Arts District",
    category: "Hotels & Travel",
    subcategory: "Luxury Hotel",
    description:
      "The JW Marriott Dallas Arts District is a premier luxury hotel in the heart of downtown Dallas, steps from the AT&T Performing Arts Center, the Nasher Sculpture Center, and the Dallas Museum of Art. Featuring 267 elegantly appointed rooms, a rooftop pool, a full-service spa, and award-winning dining at Ebb & Flow restaurant.",
    phone: "+1 (214) 999-7800",
    email: "reservations@jwmarriottdallas.com",
    website: "https://marriott.com/hotels/travel/daldt-jw-marriott-dallas-arts-district",
    address: "2001 Ross Ave",
    city: "Dallas",
    state: "TX",
    zipCode: "75201",
    hours: {
      monday: "Open 24 Hours",
      tuesday: "Open 24 Hours",
      wednesday: "Open 24 Hours",
      thursday: "Open 24 Hours",
      friday: "Open 24 Hours",
      saturday: "Open 24 Hours",
      sunday: "Open 24 Hours",
    },
    services: [
      "Luxury Rooms & Suites",
      "Rooftop Pool",
      "Full-Service Spa",
      "Fine Dining",
      "Business Center",
      "Event Spaces",
      "Concierge Service",
      "Valet Parking",
    ],
    rating: 4.6,
    reviewCount: 2134,
    established: 2018,
    featured: true,
    verified: true,
    socialMedia: {
      instagram: "https://instagram.com/jwmarriottdallas",
      facebook: "https://facebook.com/jwmarriottdallas",
    },
  },
  {
    id: "11",
    slug: "university-of-texas-austin",
    name: "The University of Texas at Austin",
    category: "Education",
    subcategory: "University",
    description:
      "The University of Texas at Austin is one of the largest and most prestigious public research universities in the United States. Founded in 1883, UT Austin enrolls over 50,000 students across 18 colleges and schools. Home to the renowned LBJ School of Public Affairs, McCombs School of Business, Cockrell School of Engineering, and the iconic UT Tower.",
    phone: "+1 (512) 471-3434",
    email: "admissions@utexas.edu",
    website: "https://utexas.edu",
    address: "110 Inner Campus Dr",
    city: "Austin",
    state: "TX",
    zipCode: "78712",
    hours: {
      monday: "8:00 AM - 5:00 PM",
      tuesday: "8:00 AM - 5:00 PM",
      wednesday: "8:00 AM - 5:00 PM",
      thursday: "8:00 AM - 5:00 PM",
      friday: "8:00 AM - 5:00 PM",
      saturday: "Closed",
      sunday: "Closed",
    },
    services: [
      "Undergraduate Programs",
      "Graduate & PhD Programs",
      "Research Centers",
      "Online Courses",
      "Campus Tours",
      "Student Housing",
      "Career Services",
      "Athletics",
    ],
    rating: 4.7,
    reviewCount: 6203,
    established: 1883,
    featured: false,
    verified: true,
    socialMedia: {
      twitter: "https://twitter.com/utaustin",
      instagram: "https://instagram.com/ut_austin",
      facebook: "https://facebook.com/UTAustin",
    },
  },
  {
    id: "12",
    slug: "tesla-service-center-houston",
    name: "Tesla Service Center Houston",
    category: "Automotive",
    subcategory: "Electric Vehicle Service",
    description:
      "Tesla's Houston Service Center provides comprehensive maintenance, repair, and diagnostics for all Tesla vehicles including Model S, Model 3, Model X, Model Y, and Cybertruck. Services include software updates, battery inspection, collision repair referrals, tire rotations, and mobile service dispatch for minor repairs at your location.",
    phone: "+1 (888) 518-3752",
    email: "service@tesla.com",
    website: "https://tesla.com/findus/location/service/houstonservicetx",
    address: "11560 Southwest Fwy",
    city: "Houston",
    state: "TX",
    zipCode: "77031",
    hours: {
      monday: "8:00 AM - 6:00 PM",
      tuesday: "8:00 AM - 6:00 PM",
      wednesday: "8:00 AM - 6:00 PM",
      thursday: "8:00 AM - 6:00 PM",
      friday: "8:00 AM - 6:00 PM",
      saturday: "9:00 AM - 5:00 PM",
      sunday: "Closed",
    },
    services: [
      "Vehicle Diagnostics",
      "Battery Inspection",
      "Tire Rotation & Replacement",
      "Software Updates",
      "Mobile Service",
      "Collision Repair Referral",
      "Loaner Vehicles",
    ],
    rating: 4.3,
    reviewCount: 1478,
    established: 2014,
    featured: false,
    verified: true,
    socialMedia: {
      twitter: "https://twitter.com/tesla",
      instagram: "https://instagram.com/teslamotors",
    },
  },
  {
    id: "13",
    slug: "neiman-marcus-dallas",
    name: "Neiman Marcus — Downtown Dallas",
    category: "Shopping & Retail",
    subcategory: "Luxury Department Store",
    description:
      "The original Neiman Marcus flagship store, founded in Dallas in 1907, remains the crown jewel of luxury retail in Texas. Spanning multiple floors in downtown Dallas, the store features the world's finest designer fashion, jewelry, beauty, and home collections. Home to the iconic Zodiac Restaurant and the beloved Christmas Book with its legendary fantasy gifts.",
    phone: "+1 (214) 741-6911",
    email: "customerservice@neimanmarcus.com",
    website: "https://neimanmarcus.com",
    address: "1618 Main St",
    city: "Dallas",
    state: "TX",
    zipCode: "75201",
    hours: {
      monday: "10:00 AM - 7:00 PM",
      tuesday: "10:00 AM - 7:00 PM",
      wednesday: "10:00 AM - 7:00 PM",
      thursday: "10:00 AM - 7:00 PM",
      friday: "10:00 AM - 8:00 PM",
      saturday: "10:00 AM - 8:00 PM",
      sunday: "12:00 PM - 6:00 PM",
    },
    services: [
      "Designer Fashion",
      "Fine Jewelry & Watches",
      "Beauty & Fragrance",
      "Home Décor",
      "Personal Shopping",
      "In-Store Restaurant",
      "Alterations",
      "Gift Wrapping",
    ],
    rating: 4.5,
    reviewCount: 3256,
    established: 1907,
    featured: true,
    verified: true,
    socialMedia: {
      instagram: "https://instagram.com/neimanmarcus",
      facebook: "https://facebook.com/neimanmarcus",
      twitter: "https://twitter.com/neimanmarcus",
    },
  },
  {
    id: "14",
    slug: "stubb-amphitheater-austin",
    name: "Stubb's Waller Creek Amphitheater",
    category: "Entertainment",
    subcategory: "Live Music Venue",
    description:
      "Stubb's Waller Creek Amphitheater is one of Austin's most iconic outdoor music venues, set against the city's famous Waller Creek. With a capacity of 2,750 under the stars, Stubb's has hosted legends from Willie Nelson to Radiohead. The venue is adjacent to Stubb's Bar-B-Q restaurant, offering authentic Texas BBQ before every show.",
    phone: "+1 (512) 480-8341",
    email: "info@stubbsaustin.com",
    website: "https://stubbsaustin.com",
    address: "801 Red River St",
    city: "Austin",
    state: "TX",
    zipCode: "78701",
    hours: {
      monday: "Event Days Only",
      tuesday: "Event Days Only",
      wednesday: "Event Days Only",
      thursday: "Event Days Only",
      friday: "Event Days Only",
      saturday: "Event Days Only",
      sunday: "Event Days Only",
    },
    services: [
      "Outdoor Amphitheater",
      "Indoor Waller Creek Amphitheater",
      "Live Concerts",
      "Comedy Shows",
      "Private Events",
      "Full Bar Service",
      "BBQ Food Service",
    ],
    rating: 4.8,
    reviewCount: 4512,
    established: 1996,
    featured: false,
    verified: true,
    socialMedia: {
      twitter: "https://twitter.com/stubbsaustin",
      instagram: "https://instagram.com/stubbsaustin",
      facebook: "https://facebook.com/stubbsaustin",
    },
  },
  {
    id: "15",
    slug: "driskill-hotel-austin",
    name: "The Driskill Hotel",
    category: "Hotels & Travel",
    subcategory: "Historic Hotel",
    description:
      "The Driskill is Austin's most historic and beloved hotel, built in 1886 by cattle baron Jesse Driskill. Listed on the National Register of Historic Places, The Driskill combines 19th-century Romanesque architecture with modern luxury. Features 189 rooms, the acclaimed 1886 Café & Bakery, The Driskill Bar, and lavish event spaces used for Texas gubernatorial balls since its opening.",
    phone: "+1 (512) 439-1234",
    email: "reservations@driskillhotel.com",
    website: "https://driskillhotel.com",
    address: "604 Brazos St",
    city: "Austin",
    state: "TX",
    zipCode: "78701",
    hours: {
      monday: "Open 24 Hours",
      tuesday: "Open 24 Hours",
      wednesday: "Open 24 Hours",
      thursday: "Open 24 Hours",
      friday: "Open 24 Hours",
      saturday: "Open 24 Hours",
      sunday: "Open 24 Hours",
    },
    services: [
      "Historic Rooms & Suites",
      "Fine Dining",
      "Historic Bar",
      "Event & Wedding Spaces",
      "Concierge Service",
      "Valet Parking",
      "Ghost Tours",
      "Business Center",
    ],
    rating: 4.6,
    reviewCount: 1897,
    established: 1886,
    featured: false,
    verified: true,
    socialMedia: {
      instagram: "https://instagram.com/driskillhotel",
      facebook: "https://facebook.com/driskillhotel",
      twitter: "https://twitter.com/driskillhotel",
    },
  },
  {
    id: "16",
    slug: "spec-wine-spirits-houston",
    name: "Spec's Wines, Spirits & Finer Foods",
    category: "Shopping & Retail",
    subcategory: "Specialty Food & Beverage",
    description:
      "Spec's is Texas's premier destination for wines, spirits, craft beers, and gourmet foods. The Houston flagship on Smith Street is one of the largest liquor and fine food stores in the United States, spanning over 80,000 square feet with more than 50,000 product selections. Family-owned since 1962, Spec's is a true Texas institution beloved by foodies and cocktail enthusiasts alike.",
    phone: "+1 (713) 526-8787",
    email: "customerservice@specsonline.com",
    website: "https://specsonline.com",
    address: "2410 Smith St",
    city: "Houston",
    state: "TX",
    zipCode: "77006",
    hours: {
      monday: "9:00 AM - 10:00 PM",
      tuesday: "9:00 AM - 10:00 PM",
      wednesday: "9:00 AM - 10:00 PM",
      thursday: "9:00 AM - 10:00 PM",
      friday: "9:00 AM - 11:00 PM",
      saturday: "9:00 AM - 11:00 PM",
      sunday: "10:00 AM - 9:00 PM",
    },
    services: [
      "Fine Wines",
      "Craft Spirits",
      "Craft Beer",
      "Gourmet Food",
      "Cheese & Charcuterie",
      "Cigars",
      "Curbside Pickup",
      "Online Ordering",
    ],
    rating: 4.8,
    reviewCount: 5630,
    established: 1962,
    featured: false,
    verified: true,
    socialMedia: {
      facebook: "https://facebook.com/specsonline",
      instagram: "https://instagram.com/specswines",
      twitter: "https://twitter.com/specsonline",
    },
  },
];

export const categories = [
  "All",
  "Home Services",
  "Food & Dining",
  "Technology",
  "Healthcare",
  "Health & Fitness",
  "Pet Services",
  "Hotels & Travel",
  "Education",
  "Automotive",
  "Shopping & Retail",
  "Entertainment",
];

export function getBusinessBySlug(slug: string): Business | undefined {
  return businesses.find((b) => b.slug === slug);
}

export function getBusinessesByCategory(category: string): Business[] {
  if (category === "All") return businesses;
  return businesses.filter((b) => b.category === category);
}
